### ISSUE TITLE
Eccezione dopo il salvataggio dell'inserimento automatico

### ISSUE THREAD

**Issue by tiarap00** [stignarnia/Webex-Launcher-Auto#22]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Process revision is not downloaded. Run BrowserFetcher.DownloadAsync or download the process manually
   at PuppeteerSharp.Launcher.<ResolveExecutablePathAsync>d__14.MoveNext() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 195
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.Launcher.<GetOrFetchBrowserExecutableAsync>d__13.MoveNext() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 177
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.Launcher.<LaunchAsync>d__8.MoveNext() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WLA_puppeteer.WLA_puppeteer.<DownloadScheduleChromium>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Webex_Launcher_Auto.Program.<>c.<<Sync>b__7_0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Webex_Launcher_Auto.Program.Sync()
   at Webex_Launcher_Auto.Forms.Home.Sync_Click(Object sender, EventArgs e)
   at Webex_Launcher_Auto.Forms.Home.Settings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.IO.FileNotFoundException: Process revision is not downloaded. Run BrowserFetcher.DownloadAsync or download the process manually
File name: 'C:\Program Files\webexlauncher\Webex Launcher\.local-chromium\Win64-884014\chrome-win\chrome.exe'
   at PuppeteerSharp.Launcher.<ResolveExecutablePathAsync>d__14.MoveNext() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 195
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.Launcher.<GetOrFetchBrowserExecutableAsync>d__13.MoveNext() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 177
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.Launcher.<LaunchAsync>d__8.MoveNext() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WLA_puppeteer.WLA_puppeteer.<DownloadScheduleChromium>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Webex_Launcher_Auto.Program.<>c.<<Sync>b__7_0>d.MoveNext()<---

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Webex-Launcher-Auto
    Assembly Version: 1.11.0.0
    Win32 Version: 1.11.0.0
    CodeBase: file:///C:/Program%20Files/webexlauncher/Webex%20Launcher/Webex-Launcher-Auto.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
PuppeteerSharp
    Assembly Version: 5.1.0.0
    Win32 Version: 5.1.0.0
    CodeBase: file:///C:/Program%20Files/webexlauncher/Webex%20Launcher/PuppeteerSharp.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
Microsoft.Bcl.AsyncInterfaces
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.45113
    CodeBase: file:///C:/Program%20Files/webexlauncher/Webex%20Launcher/Microsoft.Bcl.AsyncInterfaces.DLL
----------------------------------------
System.Threading.Tasks.Extensions
    Assembly Version: 4.2.0.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Program%20Files/webexlauncher/Webex%20Launcher/System.Threading.Tasks.Extensions.DLL
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.45113
    CodeBase: file:///C:/Program%20Files/webexlauncher/Webex%20Launcher/Microsoft.Extensions.Logging.Abstractions.DLL
----------------------------------------
Microsoft.Extensions.Logging
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.45113
    CodeBase: file:///C:/Program%20Files/webexlauncher/Webex%20Launcher/Microsoft.Extensions.Logging.DLL
----------------------------------------
Microsoft.Extensions.Options
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.45113
    CodeBase: file:///C:/Program%20Files/webexlauncher/Webex%20Launcher/Microsoft.Extensions.Options.DLL
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1.25517
    CodeBase: file:///C:/Program%20Files/webexlauncher/Webex%20Launcher/Newtonsoft.Json.DLL
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.RuntimeInformation/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by stignarnia** [comment]
Mi sa che semplicemente non è capace di trovare l'eseguibile di Chrome che cerca. Comunque quando avrò tempo piuttosto che fixare questo penso di rifarlo in MAUI per imparare quello e averlo anche multipiattaforma

**Comment by stignarnia** [comment]
Webex nuovo, quello non meetings, supporta di default la cronologia delle chiamate
